[package]
name = "webcrawler_email"
version = "0.1.1"
edition = "2024"

[dependencies]
reqwest = {version = "0.12.23", features = ["blocking"]}
scraper = "0.24.0"
rusqlite = { version = "0.37.0", features = ["bundled"] }
eframe = "0.32.3"
